name: txnduck
services:
  dev:
    container_name: txnduck-dev
    build:
      context: .
      target: dev-setup
      dockerfile: ./Containerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
